/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedDocumentNode } from "@graphql-typed-document-node/core";
type addQAInputInputType = {
    question: string;
    answer: string;
};
export type addQA = {
    addQA: (QABasicData) | null;
};
export type addQAVariables = {
    input: addQAInputInputType;
};
export type addQADocument = TypedDocumentNode<addQA, addQAVariables>;
export type QABasicData = {
    _id: any | null;
    question: string | null;
    answer: string | null;
    createdBy: (UserBasicData) | null;
};
export type UserBasicData = {
    _id: string;
    name: string | null;
    email: string | null;
    username: string | null;
};
