/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedDocumentNode } from "@graphql-typed-document-node/core";
export type authenticate = {
    _checkAuth: string | null;
};
export type authenticateVariables = {};
export type authenticateDocument = TypedDocumentNode<authenticate, authenticateVariables>;
