/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedDocumentNode } from "@graphql-typed-document-node/core";
export type connection = {
    connection: string;
};
export type connectionVariables = {};
export type connectionDocument = TypedDocumentNode<connection, connectionVariables>;
