/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedDocumentNode } from "@graphql-typed-document-node/core";
export type currentUser = {
    currentUser: (UserBasicData) | null;
};
export type currentUserVariables = {};
export type currentUserDocument = TypedDocumentNode<currentUser, currentUserVariables>;
export type UserBasicData = {
    _id: string;
    name: string | null;
    email: string | null;
    username: string | null;
};
