/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedDocumentNode } from "@graphql-typed-document-node/core";
type InputQueryParamsInputType = {
    limit?: number | null;
    skip?: number | null;
    sort?: (string | null)[] | null;
    where?: any | null;
};
export type listOwnQA = {
    listOwnQA: ((QABasicData) | null)[] | null;
};
export type listOwnQAVariables = {
    params: InputQueryParamsInputType;
};
export type listOwnQADocument = TypedDocumentNode<listOwnQA, listOwnQAVariables>;
export type QABasicData = {
    _id: any | null;
    question: string | null;
    answer: string | null;
    createdBy: (UserBasicData) | null;
};
export type UserBasicData = {
    _id: string;
    name: string | null;
    email: string | null;
    username: string | null;
};
