/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedDocumentNode } from "@graphql-typed-document-node/core";
type userCredentialsInputType = {
    username: string;
    password: any;
};
export type login = {
    login: string | null;
};
export type loginVariables = {
    userCredentials: userCredentialsInputType;
};
export type loginDocument = TypedDocumentNode<login, loginVariables>;
