/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type QABasicData = {
    _id: any | null;
    question: string | null;
    answer: string | null;
    createdBy: (UserBasicData) | null;
};
export type UserBasicData = {
    _id: string;
    name: string | null;
    email: string | null;
    username: string | null;
};
