/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedDocumentNode } from "@graphql-typed-document-node/core";
export type suggestAiAnswer = {
    suggestAiAnswer: string | null;
};
export type suggestAiAnswerVariables = {
    question: string;
};
export type suggestAiAnswerDocument = TypedDocumentNode<suggestAiAnswer, suggestAiAnswerVariables>;
