/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedDocumentNode } from "@graphql-typed-document-node/core";
type updateQAInputInputType = {
    _id: any;
    question: string;
    answer: string;
};
export type updateQA = {
    updateQA: (QABasicData) | null;
};
export type updateQAVariables = {
    input: updateQAInputInputType;
};
export type updateQADocument = TypedDocumentNode<updateQA, updateQAVariables>;
export type QABasicData = {
    _id: any | null;
    question: string | null;
    answer: string | null;
    createdBy: (UserBasicData) | null;
};
export type UserBasicData = {
    _id: string;
    name: string | null;
    email: string | null;
    username: string | null;
};
